### ISSUE TITLE
Проверка 1го ДЗ

### ISSUE THREAD

**Issue by Disadvantaged** [jamirhan/Automata#1]
Не хватает анализа сложности в алгоритме.
Что-то в последнем пункте совсем не очевидно то, что слово является префиксом слова из языка. Распиши подробнее вторую половину
https://github.com/jamirhan/Automata/blob/895a4f42d852a5b38c83f83792a6f5809b3a7d05/Automata.h#L389 -- функции не пишутся в хедерах обычно, а выносятся в .cpp файлы.
https://github.com/jamirhan/Automata/blob/895a4f42d852a5b38c83f83792a6f5809b3a7d05/Automata.h#L51 -- тут не подошли бы unordered_-аналоги?
https://github.com/jamirhan/Automata/blob/895a4f42d852a5b38c83f83792a6f5809b3a7d05/Automata.h#L39 -- это излишне. Можно использовать Aggregate initialization. А с 20х плюсов вообще красиво выглядит.
https://github.com/jamirhan/Automata/blob/895a4f42d852a5b38c83f83792a6f5809b3a7d05/main.cpp#L12 -- пробелы?
https://github.com/jamirhan/Automata/blob/895a4f42d852a5b38c83f83792a6f5809b3a7d05/Automata.h#L89 -- чёт ссылки скачут

За тесты лайк!)

**Comment by jamirhan** [comment]
вроде исправил, кроме замечания про unordered - этот маневр обошелся бы мне в переписывании всего кода, вроде оно того не стоит

**Comment by Disadvantaged** [comment]
Асимптотику стоит обобщить, а то E_n и V_n тебе не пользователь даёт, а ты их получаешь в ходе алгоритма.
То есть, итоговая формула должна зависеть только от исходного автомата.
Также заметил, что у тебя в классе очень много публичных методов. Это немного размывает его интерфейс и непонятно становится как взаимодействовать с автоматом. Предлагаю спрятать все детали реализации в приватную секцию.

**Comment by jamirhan** [comment]
Исправил асимптотику, второго замечания не понял - каждый публичный метод и задумывался публичным.

**Comment by Disadvantaged** [comment]
Да, сорри, пересмотрел и понял, что всё по делу.

**Comment by Disadvantaged** [comment]
Всё вышло классно, закрываю issue. На будущее, создавай пожалуйста PR =)
